#name: docker image build and push
## This workflow is triggered on pushes to the repository.
#on:
#  schedule:
#    - cron: '0 8 * * *'
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - '**'

jobs:
  git-sync:
    name: git-sync
    # This job runs on Linux
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: status-im/nimbus-eth2
          path: 'nimbus-docker/nimbus-eth2'
      - shell: bash
        run: |
          cd nimbus-docker/nimbus-eth2
          make -j8 update
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker-build-push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./nimbus-docker/Dockerfile
          tags: parithoshj/nimbus-docker-genesis:latest
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}