#name: docker image build and push
## This workflow is triggered on pushes to the repository.
#on:
#  schedule:
#    - cron: '0 8 * * *'
# This workflow is triggered on pushes to the repository.
on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  git-sync:
    name: git-sync
    # This job runs on Linux
    runs-on: self-hosted
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Running update
        shell: bash
        run: |
          ls
      - name: Check out my other private repo
        uses: actions/checkout@v2
        with:
          repository: status-im/nimbus-eth2
          path: 'nimbus-eth2'
      - name: Running update
        shell: bash
        run: |
          cd nimbus-eth2
          make -j8 update
      - name: Build and push
        id: gen_tags
        run: |
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='["parithoshj/nimbus-docker-genesis:latest","'${GITHUB_REF/refs\/tags\//}'"]'
          else
            TAGS='["parithoshj/nimbus-docker-genesis:latest"]'
          fi
          echo '::set-output name=tags::'$TAGS
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker-build-push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
          push: true
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}